services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=ashwathi
      - POSTGRES_PASSWORD=sunbeam
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl:
    build: .
    command: http://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db
    # restart: always

volumes:
  db_data:


